"""build_components.py — generators driven by the canonical components/ tree.

Generators (deterministic, safe to re-run):
  --gen-fplib   kicad/fp-lib-table from the vendored kicad/footprints/*.pretty libs,
                namespaced POGO_* to avoid KiCad stock-library nickname collisions.
  --gen-bom     kicad/pogo-bom.csv — manufacturing BOM from specs/components.yaml
                (authoritative) enriched by the components/ registry (MPN, footprint
                lib-id, manufacturer/supplier, datasheet). Also writes docs/pogo-bom.csv
                (identical copy consumed by the docs/bom.html Pages viewer).
  --all         both of the above.
  --check       fail if any generated artifact is stale (CI drift gate).

specs/components.yaml stays hand-maintained; the BOM is a derived view of it.
Per-block BOM tables and components.yaml generation remain deferred.
"""

from __future__ import annotations

import csv
import io
import sys
from pathlib import Path

import components  # registry loader (same dir)

_REPO = Path(__file__).resolve().parent.parent
_FP_ROOT = _REPO / "kicad" / "footprints"
_FP_LIB_TABLE = _REPO / "kicad" / "fp-lib-table"
_BOM_CSV = _REPO / "kicad" / "pogo-bom.csv"
_DOCS_BOM_CSV = _REPO / "docs" / "pogo-bom.csv"   # copy consumed by docs/bom.html (Pages)

_BANNER = "# GENERATED by tools/build_components.py --gen-fplib — DO NOT EDIT."

_BOM_COLS = ["Board", "Ref", "Qty", "MPN", "Value", "Package", "Footprint",
             "Manufacturer", "Supplier", "Datasheet", "Block", "Function"]


def _clean(v) -> str:
    s = "" if v is None else str(v)
    return "" if s == "~" else s


def gen_bom() -> str:
    """Manufacturing BOM (CSV) from specs/components.yaml enriched by the registry.

    components.yaml stays the authoritative source; registry parts (matched via their
    matches[] list) add MPN / manufacturer / supplier / KiCad footprint id / datasheet.
    Rows follow components.yaml order (already board- then block-grouped).
    """
    buf = io.StringIO()
    w = csv.DictWriter(buf, fieldnames=_BOM_COLS, lineterminator="\n")
    w.writeheader()
    for c in components.bom_components():
        part_str = c.get("part")
        reg = components.part_for(part_str) if part_str and part_str != "~" else None
        fp = ""
        if reg and reg.get("footprint"):
            fp = f"POGO_{reg['footprint']['lib']}:{reg['footprint']['name']}"
        ds = (reg.get("datasheet") or {}).get("url", "") if reg else ""
        w.writerow({
            "Board": _clean(c.get("board")),
            "Ref": _clean(c.get("ref")),
            "Qty": _clean(c.get("qty", 1)),
            "MPN": _clean(reg.get("mpn") if reg else (part_str if part_str != "~" else "")),
            "Value": _clean(c.get("val")),
            "Package": _clean(c.get("pkg")),
            "Footprint": fp,
            "Manufacturer": _clean(reg.get("manufacturer") if reg else ""),
            "Supplier": _clean(reg.get("supplier") if reg else ""),
            "Datasheet": ds,
            "Block": _clean(c.get("block")),
            "Function": _clean(c.get("fn")),
        })
    return buf.getvalue()


def _pretty_libs() -> list[str]:
    """Sorted names of *.pretty footprint libraries under kicad/footprints/."""
    return sorted(p.name[: -len(".pretty")] for p in _FP_ROOT.glob("*.pretty") if p.is_dir())


def gen_fplib() -> str:
    """Return the fp-lib-table text (KiCad s-expr) for the vendored libraries."""
    lines = [
        f";; {_BANNER[2:]}",
        "(fp_lib_table",
        "  (version 7)",
    ]
    for lib in _pretty_libs():
        uri = f"${{KIPRJMOD}}/footprints/{lib}.pretty"
        lines.append(
            f'  (lib (name "POGO_{lib}")(type "KiCad")(uri "{uri}")(options "")(descr "POGO vendored {lib}"))'
        )
    lines.append(")")
    return "\n".join(lines) + "\n"


def _check_balanced(text: str) -> bool:
    return text.count("(") == text.count(")")


def _write_fplib() -> int:
    text = gen_fplib()
    if not _check_balanced(text):
        print("ERROR: generated fp-lib-table has unbalanced parentheses")
        return 1
    _FP_LIB_TABLE.write_text(text)
    print(f"Wrote {_FP_LIB_TABLE.relative_to(_REPO)} ({text.count('(lib ')} libraries, POGO_* namespaced).")
    return 0


def _write_bom() -> int:
    text = gen_bom()
    _BOM_CSV.write_text(text)
    _DOCS_BOM_CSV.write_text(text)   # keep the Pages copy (docs/bom.html) in sync
    rows = text.count("\n") - 1
    print(f"Wrote {_BOM_CSV.relative_to(_REPO)} + {_DOCS_BOM_CSV.relative_to(_REPO)} ({rows} BOM rows).")
    return 0


def _check() -> int:
    """Verify generated artifacts are up to date with the registry/components.yaml."""
    errs = []
    if (not _FP_LIB_TABLE.exists()) or _FP_LIB_TABLE.read_text() != gen_fplib():
        errs.append("kicad/fp-lib-table is stale — run: build_components.py --gen-fplib")
    bom = gen_bom()
    if (not _BOM_CSV.exists()) or _BOM_CSV.read_text() != bom:
        errs.append("kicad/pogo-bom.csv is stale — run: build_components.py --gen-bom")
    if (not _DOCS_BOM_CSV.exists()) or _DOCS_BOM_CSV.read_text() != bom:
        errs.append("docs/pogo-bom.csv is stale — run: build_components.py --gen-bom")
    if errs:
        print("BUILD-COMPONENTS CHECK — FAIL:")
        for e in errs:
            print(f"  - {e}")
        return 1
    print("BUILD-COMPONENTS CHECK — OK (fp-lib-table + BOM up to date).")
    return 0


def _main(argv: list[str]) -> int:
    if "--check" in argv:
        return _check()
    rc = 0
    if "--gen-fplib" in argv or "--all" in argv:
        rc |= _write_fplib()
    if "--gen-bom" in argv or "--all" in argv:
        rc |= _write_bom()
    if rc == 0 and not any(a.startswith("--gen") or a == "--all" for a in argv):
        print(__doc__)
        print("usage: python3 tools/build_components.py [--gen-fplib] [--gen-bom] [--all] [--check]")
    return rc


if __name__ == "__main__":
    sys.exit(_main(sys.argv[1:]))
