"""build_components.py — generators driven by the canonical components/ tree.

Phase 1 generators:
  --gen-fplib   write kicad/fp-lib-table from the vendored kicad/footprints/*.pretty
                libraries, namespaced POGO_* to avoid collisions with KiCad's stock
                global libraries.

Deterministic output (sorted), safe to re-run. Generated files carry a DO-NOT-EDIT
banner. components.yaml and per-block BOM tables are intentionally NOT generated in
Phase 1 (see /tmp/components_plan_final.md / the components README).
"""

from __future__ import annotations

import sys
from pathlib import Path

_REPO = Path(__file__).resolve().parent.parent
_FP_ROOT = _REPO / "kicad" / "footprints"
_FP_LIB_TABLE = _REPO / "kicad" / "fp-lib-table"

_BANNER = "# GENERATED by tools/build_components.py --gen-fplib — DO NOT EDIT."


def _pretty_libs() -> list[str]:
    """Sorted names of *.pretty footprint libraries under kicad/footprints/."""
    return sorted(p.name[: -len(".pretty")] for p in _FP_ROOT.glob("*.pretty") if p.is_dir())


def gen_fplib() -> str:
    """Return the fp-lib-table text (KiCad s-expr) for the vendored libraries."""
    lines = [
        f";; {_BANNER[2:]}",
        "(fp_lib_table",
        "  (version 7)",
    ]
    for lib in _pretty_libs():
        uri = f"${{KIPRJMOD}}/footprints/{lib}.pretty"
        lines.append(
            f'  (lib (name "POGO_{lib}")(type "KiCad")(uri "{uri}")(options "")(descr "POGO vendored {lib}"))'
        )
    lines.append(")")
    return "\n".join(lines) + "\n"


def _check_balanced(text: str) -> bool:
    return text.count("(") == text.count(")")


def _main(argv: list[str]) -> int:
    if "--gen-fplib" in argv or "--all" in argv:
        text = gen_fplib()
        if not _check_balanced(text):
            print("ERROR: generated fp-lib-table has unbalanced parentheses")
            return 1
        _FP_LIB_TABLE.write_text(text)
        n = text.count("(lib ")
        print(f"Wrote {_FP_LIB_TABLE.relative_to(_REPO)} ({n} libraries, POGO_* namespaced).")
        return 0

    print(__doc__)
    print("usage: python3 tools/build_components.py --gen-fplib")
    return 0


if __name__ == "__main__":
    sys.exit(_main(sys.argv[1:]))
