"""build_components.py — generators driven by the canonical components/ tree.

Generators (deterministic, safe to re-run):
  --gen-fplib   kicad/fp-lib-table from the vendored components/footprints/*.pretty libs,
                namespaced POGO_* to avoid KiCad stock-library nickname collisions.
  --gen-bom     kicad/pogo-bom.csv — manufacturing BOM from specs/components.yaml
                (authoritative) enriched by the components/ registry (MPN, footprint
                lib-id, manufacturer/supplier, datasheet). Also writes docs/pogo-bom.csv
                (identical copy consumed by the docs/bom.html Pages viewer).
  --gen-fp      docs/footprints/<slug>.svg — one rendered land-pattern per vendored
                footprint, used by the BOM viewer's hover popups.
  --gen-panel   docs/Pogo.svg — copy of the panel art, embedded by docs/panel.html.
  --all         all of the above.
  --check       fail if any generated artifact is stale (CI drift gate).

specs/components.yaml stays hand-maintained; the BOM is a derived view of it.
Per-block BOM tables and components.yaml generation remain deferred.
"""

from __future__ import annotations

import csv
import io
import sys
from pathlib import Path

import components       # registry loader (same dir)
import footprint_svg    # .kicad_mod -> SVG renderer (same dir)

_REPO = Path(__file__).resolve().parent.parent
_FP_ROOT = _REPO / "components" / "footprints"
_FP_LIB_TABLE = _REPO / "kicad" / "fp-lib-table"
_BOM_CSV = _REPO / "kicad" / "pogo-bom.csv"
_DOCS_BOM_CSV = _REPO / "docs" / "pogo-bom.csv"    # copy consumed by docs/bom.html (Pages)
_DOCS_FP_DIR = _REPO / "docs" / "footprints"       # pre-rendered footprint SVGs (BOM viewer popups)
_PANEL_SVG = _REPO / "plugin" / "res" / "Pogo.svg"  # generated panel art (build_panel --resource)
_DOCS_PANEL_SVG = _REPO / "docs" / "Pogo.svg"       # copy embedded by docs/panel.html (Pages)

_BANNER = "# GENERATED by tools/build_components.py --gen-fplib — DO NOT EDIT."
_MANIFEST = _REPO / "GENERATED.md"

# Build graph / sources-of-truth map. (artifact, generator, source(s), --check gate)
_GENERATED = [
    ("kicad/fp-lib-table", "build_components.py --gen-fplib", "components/footprints/*.pretty", "build_components.py --check"),
    ("kicad/pogo-bom.csv", "build_components.py --gen-bom", "specs/components.yaml + components/parts", "build_components.py --check"),
    ("docs/pogo-bom.csv", "build_components.py --gen-bom", "(copy of kicad/pogo-bom.csv)", "build_components.py --check"),
    ("docs/footprints/*.svg", "build_components.py --gen-fp", "components/footprints/*.pretty", "build_components.py --check"),
    ("docs/Pogo.svg", "build_components.py --gen-panel", "plugin/res/Pogo.svg", "build_components.py --check"),
    ("kicad/pogo-*.kicad_sch", "kicad/generate_schematic.py", "specs/block-*/*.nets.yaml", "generate_schematic.py --check"),
    ("specs/block-6/block-6.nets.yaml", "kicad/gen_block6.py", "(authored generator script)", "generate_schematic.py --check"),
    ("plugin/res/Pogo.svg + Pogo-source.svg", "build_panel.py --resource --mfr", "tools/panel-data.yaml", "build_panel.py --check (DRC)"),
    ("design/panel-debug.html", "build_panel.py --design", "tools/panel-data.yaml", "build_panel.py --check (DRC)"),
]


def gen_manifest() -> str:
    """GENERATED.md — the build graph. Authored files NOT listed here are source of truth."""
    out = [
        "# Generated artifacts (build graph)",
        "",
        "<!-- GENERATED by tools/build_components.py --gen-manifest — DO NOT EDIT. -->",
        "",
        "These files are **derived** — never hand-edit them; regenerate from their source.",
        "They are flagged `linguist-generated` in `.gitattributes`. Every other tracked file",
        "is authored source of truth. CI `--check` gates keep each row reproducible.",
        "",
        "| Artifact | Generator | Source(s) | --check gate |",
        "|---|---|---|---|",
    ]
    for art, gen, src, gate in _GENERATED:
        out.append(f"| `{art}` | `{gen}` | {src} | `{gate}` |")
    out.append("")
    return "\n".join(out) + "\n"

_BOM_COLS = ["Board", "Ref", "Type", "Qty", "MPN", "Value", "Package", "Footprint",
             "Manufacturer", "Supplier", "Datasheet", "Block", "Function"]

# Part type by reference-designator prefix (longest prefix wins: LED before L, RV before R).
_TYPE_PREFIXES = [
    ("LED", "LED"), ("RV", "Trimpot/Pot"), ("SW", "Switch"),
    ("R", "Resistor"), ("C", "Capacitor"), ("D", "Diode"),
    ("U", "IC"), ("J", "Jack"), ("Q", "Transistor"), ("L", "Inductor"),
]


def _part_type(ref: str) -> str:
    r = ref or ""
    for pfx, t in _TYPE_PREFIXES:
        if r.startswith(pfx):
            return t
    return "Other"


def _clean(v) -> str:
    s = "" if v is None else str(v)
    return "" if s == "~" else s


def gen_bom() -> str:
    """Manufacturing BOM (CSV) from specs/components.yaml enriched by the registry.

    components.yaml stays the authoritative source; registry parts (matched via their
    matches[] list) add MPN / manufacturer / supplier / KiCad footprint id / datasheet.
    Rows follow components.yaml order (already board- then block-grouped).
    """
    buf = io.StringIO()
    w = csv.DictWriter(buf, fieldnames=_BOM_COLS, lineterminator="\n")
    w.writeheader()
    for c in components.bom_components():
        part_str = c.get("part")
        reg = components.part_for(part_str) if part_str and part_str != "~" else None
        fp = ""
        if reg and reg.get("footprint"):
            fp = f"POGO_{reg['footprint']['lib']}:{reg['footprint']['name']}"
        ds = (reg.get("datasheet") or {}).get("url", "") if reg else ""
        w.writerow({
            "Board": _clean(c.get("board")),
            "Ref": _clean(c.get("ref")),
            "Type": _part_type(_clean(c.get("ref"))),
            "Qty": _clean(c.get("qty", 1)),
            "MPN": _clean(reg.get("mpn") if reg else (part_str if part_str != "~" else "")),
            "Value": _clean(c.get("val")),
            "Package": _clean(c.get("pkg")),
            "Footprint": fp,
            "Manufacturer": _clean(reg.get("manufacturer") if reg else ""),
            "Supplier": _clean(reg.get("supplier") if reg else ""),
            "Datasheet": ds,
            "Block": (", ".join(c["block"]) if isinstance(c.get("block"), list) else _clean(c.get("block"))),
            "Function": _clean(c.get("fn")),
        })
    return buf.getvalue()


def _pretty_libs() -> list[str]:
    """Sorted names of *.pretty footprint libraries under components/footprints/."""
    return sorted(p.name[: -len(".pretty")] for p in _FP_ROOT.glob("*.pretty") if p.is_dir())


def gen_fplib() -> str:
    """Return the fp-lib-table text (KiCad s-expr) for the vendored libraries."""
    lines = [
        f";; {_BANNER[2:]}",
        "(fp_lib_table",
        "  (version 7)",
    ]
    for lib in _pretty_libs():
        uri = f"${{KIPRJMOD}}/../components/footprints/{lib}.pretty"
        lines.append(
            f'  (lib (name "POGO_{lib}")(type "KiCad")(uri "{uri}")(options "")(descr "POGO vendored {lib}"))'
        )
    lines.append(")")
    return "\n".join(lines) + "\n"


def _check_balanced(text: str) -> bool:
    return text.count("(") == text.count(")")


def _write_fplib() -> int:
    text = gen_fplib()
    if not _check_balanced(text):
        print("ERROR: generated fp-lib-table has unbalanced parentheses")
        return 1
    _FP_LIB_TABLE.write_text(text)
    print(f"Wrote {_FP_LIB_TABLE.relative_to(_REPO)} ({text.count('(lib ')} libraries, POGO_* namespaced).")
    return 0


def _write_bom() -> int:
    text = gen_bom()
    _BOM_CSV.write_text(text)
    _DOCS_BOM_CSV.write_text(text)   # keep the Pages copy (docs/bom.html) in sync
    rows = text.count("\n") - 1
    print(f"Wrote {_BOM_CSV.relative_to(_REPO)} + {_DOCS_BOM_CSV.relative_to(_REPO)} ({rows} BOM rows).")
    return 0


def _write_footprints() -> int:
    """Pre-render every vendored footprint to docs/footprints/<slug>.svg."""
    svgs = footprint_svg.render_all()
    _DOCS_FP_DIR.mkdir(parents=True, exist_ok=True)
    for sl, svg in svgs.items():
        (_DOCS_FP_DIR / f"{sl}.svg").write_text(svg)
    print(f"Wrote {len(svgs)} footprint SVGs to {_DOCS_FP_DIR.relative_to(_REPO)}/.")
    return 0


def _write_panel() -> int:
    """Copy the generated panel art into docs/ for the embedded panel viewer."""
    if not _PANEL_SVG.exists():
        print(f"NOTE: {_PANEL_SVG.relative_to(_REPO)} missing — run build_panel.py --resource first.")
        return 1
    _DOCS_PANEL_SVG.write_text(_PANEL_SVG.read_text())
    print(f"Wrote {_DOCS_PANEL_SVG.relative_to(_REPO)} (panel art copy).")
    return 0


def _check() -> int:
    """Verify generated artifacts are up to date with the registry/components.yaml."""
    errs = []
    if _PANEL_SVG.exists() and ((not _DOCS_PANEL_SVG.exists()) or
                                _DOCS_PANEL_SVG.read_text() != _PANEL_SVG.read_text()):
        errs.append("docs/Pogo.svg is stale — run: build_components.py --gen-panel")
    if (not _FP_LIB_TABLE.exists()) or _FP_LIB_TABLE.read_text() != gen_fplib():
        errs.append("kicad/fp-lib-table is stale — run: build_components.py --gen-fplib")
    bom = gen_bom()
    if (not _BOM_CSV.exists()) or _BOM_CSV.read_text() != bom:
        errs.append("kicad/pogo-bom.csv is stale — run: build_components.py --gen-bom")
    if (not _DOCS_BOM_CSV.exists()) or _DOCS_BOM_CSV.read_text() != bom:
        errs.append("docs/pogo-bom.csv is stale — run: build_components.py --gen-bom")
    svgs = footprint_svg.render_all()
    for sl, svg in svgs.items():
        f = _DOCS_FP_DIR / f"{sl}.svg"
        if (not f.exists()) or f.read_text() != svg:
            errs.append(f"docs/footprints/{sl}.svg is stale — run: build_components.py --gen-fp")
    expected = {f"{sl}.svg" for sl in svgs}
    if _DOCS_FP_DIR.is_dir():
        for f in _DOCS_FP_DIR.glob("*.svg"):
            if f.name not in expected:
                errs.append(f"docs/footprints/{f.name} is orphaned — remove it")
    if (not _MANIFEST.exists()) or _MANIFEST.read_text() != gen_manifest():
        errs.append("GENERATED.md is stale — run: build_components.py --gen-manifest")
    if errs:
        print("BUILD-COMPONENTS CHECK — FAIL:")
        for e in errs:
            print(f"  - {e}")
        return 1
    print("BUILD-COMPONENTS CHECK — OK (fp-lib-table + BOM + footprint SVGs + manifest up to date).")
    return 0


def _write_manifest() -> int:
    _MANIFEST.write_text(gen_manifest())
    print(f"Wrote {_MANIFEST.relative_to(_REPO)} ({len(_GENERATED)} artifacts).")
    return 0


def _main(argv: list[str]) -> int:
    if "--check" in argv:
        return _check()
    rc = 0
    if "--gen-fplib" in argv or "--all" in argv:
        rc |= _write_fplib()
    if "--gen-bom" in argv or "--all" in argv:
        rc |= _write_bom()
    if "--gen-fp" in argv or "--all" in argv:
        rc |= _write_footprints()
    if "--gen-panel" in argv or "--all" in argv:
        rc |= _write_panel()
    if "--gen-manifest" in argv or "--all" in argv:
        rc |= _write_manifest()
    if rc == 0 and not any(a.startswith("--gen") or a == "--all" for a in argv):
        print(__doc__)
        print("usage: python3 tools/build_components.py [--gen-fplib] [--gen-bom] [--all] [--check]")
    return rc


if __name__ == "__main__":
    sys.exit(_main(sys.argv[1:]))
